/**
 * E2E — `report --white-label` is a STATISTICS-ONLY, fingerprint- AND
 * recommendation-free client snapshot, leak-free BY CONSTRUCTION (no manual
 * scrub). The deliverable ships under the legend of a self-made local stats
 * tool, so ANY consulting / outreach / advisory verb in the RENDERED output
 * (HTML *and* MARKDOWN) breaks the legend exactly like a tool fingerprint does.
 *
 * White-label is a SUPERSET of --public. On top of suppressing the cost card +
 * source-path footnotes, it must additionally remove, from BOTH served files:
 *
 *   (1) every tool/agency fingerprint — the «aeo-platform» masthead mark,
 *       version, colophon wordmark, repo "open source" link, «Generated by …»;
 *   (2) the entire Webappski / Mission-Control bridge (<article id="mc-bridge">
 *       + the "Webappski plan" fork + commerce CTA);
 *   (3) the recommendation / outreach CLASS — every advisory verb that renders:
 *       «Pitch the top 3», «Outreach move», «Where to get mentioned»,
 *       «guest post», «concentrate outreach», «push for inclusion»,
 *       «pitch … first to convert», «closing the gap», «defend it», etc. This
 *       spans the three citation sections (Domain SOV / Categories / Canonical
 *       Sources), the Competitors subheading, the hero narrative, and the
 *       HTML-only hero "Lift opportunities" KPI + the listicle "Top gap" cell.
 *       The dead `.outreach-*` CSS rules are stripped too (inert, but they are
 *       literal «outreach» text a whole-file scrub would flag).
 *
 * It must KEEP the statistics in the same layout, under a neutral, parameterizable
 * title, with an honest methodology footer.
 *
 * The denylist below is a REGRESSION TRIPWIRE, not the class boundary. The class
 * is "advisory copy that renders in white-label" and is closed at-source in
 * lib/report/{sections,html,markdown}.js (gated on whiteLabel). The seed is built
 * to FORCE the advisory branches to render in the DEFAULT report (concentrated
 * single-category listicle pool, top-3 ≥60% share, named>0 AND src>0,
 * topCanonicalSources present, citationClassification absent) — so the two-sided
 * assertions and the per-gate mutation check below have real teeth instead of
 * false-passing because the branch never fired.
 *
 * The test is TWO-SIDED on purpose: each denylist token is asserted PRESENT in
 * the default report AND ABSENT in --white-label, for HTML and MD alike. A
 * one-sided "absent" test false-passes if --white-label silently stops being
 * wired (the surface would be absent in both because the seed never produced it),
 * or if a broken signature strips the copy from the DEFAULT report too.
 *
 * Mutation-sanity (run by hand to confirm teeth) — each MUST go RED. Verified
 * 2026-06-18 by pulling each gate, `node --test`, observing RED, restoring:
 *   - sections.js sectionDomainShareOfVoice: drop the `opts.whiteLabel ? … : …`
 *     sub → «Pitching the top 3 … Outreach templates» returns to white-label MD.
 *   - sections.js sectionDomainCategories: drop the whiteLabel column-gate →
 *     «Outreach move» column + per-row playbook returns.
 *   - sections.js sectionCanonicalSources: drop the whiteLabel branch →
 *     «Where to get mentioned» + «guest post» + «fastest path» return.
 *   - sections.js sectionCompetitors: drop the whiteLabel sub → «invest …
 *     closing the gap» returns.
 *   - html.js narrativeFor: drop the `if (whiteLabel)` block → «push for
 *     first-position / pitch … to convert» returns to the hero narrative.
 *   - html.js: change `if (!whiteLabel)` back to unconditional on the Lift KPI →
 *     «Pitch those publishers / to convert» returns.
 *   - html.js: change `if (!whiteLabel && top4Domains.length>0)` back to drop the
 *     whiteLabel guard → «push for inclusion / outreach is the lift» returns.
 *   - html.js domainTitle/categorySub: drop the `if (whiteLabel)` block → «Pitch
 *     the top 3 first» / «concentrate outreach» / «lift compounds» return.
 *   - html.js CSS strip: drop the `.outreach-*` strip → «.outreach-…» dead CSS
 *     returns to the white-label <style>.
 *   - sections.js sectionRunVerdict: drop the `whiteLabel ? stat : stat+advisory`
 *     branch on the lift note → «the shortest lift on this report …» returns to
 *     the white-label MD run verdict (verified RED 2026-08-26).
 *
 * Pure file-write + subprocess; no network, no live API.
 */
import test from 'node:test';
import assert from 'node:assert';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  withTmpProject,
  spawnCli,
  assertExitCode,
  responsesDateDir,
  reportsDateDir,
  todayDateString,
} from './_helpers.js';

const KEYS = { GEMINI_API_KEY: 'test-key-do-not-use-real', OPENAI_API_KEY: 'test-key-do-not-use-real' };

const DOMAIN = 'testbrand.com';

// Fingerprint denylist — tool / agency / Mission-Control identity. Must produce
// ZERO matches in BOTH the white-label HTML and MD.
const FINGERPRINT_DENYLIST = [
  /aeo-platform/i,
  /@webappski/i,
  /webappski/i,
  /mission ?control/i,
  /mc-bridge/i,
  /\blib\//,
  /\$\s*\/\s*run/,
  /session.?cost/i,
  /\bnpm i /,
  /generated by/i,
];

// Advisory / outreach / recommendation denylist — the consulting voice that
// breaks the "self-made stats tool" legend. ZERO matches in BOTH white-label
// files. NOTE: `/recommend/i` is intentionally INCLUDED and the seed below is
// built to NOT put "recommend" in any verbatim engine quote, so a blanket ban is
// valid here (on real Gcore data, "recommended …" appears only inside verbatim
// AI-engine rationale — measured data — and is correctly preserved).
const ADVISORY_DENYLIST = [
  /outreach/i,
  /\bpitch/i,
  /guest post/i,
  /recommend/i,
  /Outreach templates/i,
  /concentrate outreach/i,
  /push for/i,
  /fastest path/i,
  /lift compounds/i,
  /defend it/i,
  /to convert/i,
  /reverse-engineer/i,
  /highest-leverage/i,
  /Where to get mentioned/i,
  /consideration set/i,
  /closing the gap/i,
  /shortest lift/i,
];

// Seed designed to FORCE every advisory branch to render in the DEFAULT report:
//   - topDomains: all review-slug (= listicle) hosts → single category, and the
//     listicle "Top gap" cell renders with named>0; shares set so
//     top1<0.30 AND top1+top2+top3 ≥ 0.60 → domainTitle="Pitch the top 3 first".
//   - topCanonicalSources: on-category, non-own, non-denylisted → "Where to get
//     mentioned" + "guest post" copy renders.
//   - citationClassification ABSENT → the on-category filter does not drop the
//     canonical sources.
//   - results: 1 yes + 1 src → coverage.yes>0 (listicle named branch + healthy
//     narrative tail) AND coverage.src>0 (hero Lift KPI renders).
//   - topCompetitors: a trailing competitor for the Competitors barchart.
//   - NO "recommend" / outreach text in any responseExcerpt / sentiment.
function seedSummary(dir) {
  const today = todayDateString();
  const dd = responsesDateDir(dir, DOMAIN, today);
  mkdirSync(dd, { recursive: true });
  const summary = {
    date: today,
    brand: 'TestBrand',
    domain: 'testbrand.com',
    score: 50,
    mentions: 1,
    total: 2,
    sessionCostUsd: 1.98,
    costByModel: [
      { provider: 'openai', model: 'gpt-5-search-api', label: 'ChatGPT', requests: 13, inputTokens: 215476, outputTokens: 16866, costUsd: 0.54 },
      { provider: 'gemini', model: 'gemini-3.5-flash', label: 'Gemini', requests: 13, inputTokens: 159, outputTokens: 24889, costUsd: 0.01 },
    ],
    // Concentrated single-category (all review-slug = listicle) pool.
    // Shares: top1 0.25 (<0.30) · top1+2+3 = 0.25+0.21+0.18 = 0.64 (≥0.60).
    topDomains: [
      { host: 'g2.com',          count: 25, share: 0.25 },
      { host: 'capterra.com',    count: 21, share: 0.21 },
      { host: 'trustradius.com', count: 18, share: 0.18 },
      { host: 'getapp.com',      count: 10, share: 0.10 },
      { host: 'softwareadvice.com', count: 8, share: 0.08 },
    ],
    // On-category, non-own, non-denylisted citation hosts → sectionCanonicalSources
    // renders its "Where to get mentioned" / "Your action" pitch copy.
    topCanonicalSources: [
      { url: 'https://g2.com/categories/test', count: 25 },
      { url: 'https://capterra.com/p/test', count: 21 },
      { url: 'https://trustradius.com/products/test', count: 18 },
    ],
    topCompetitors: [
      { name: 'RivalCo', count: 6 },
    ],
    // llmActions present → buildHtmlSummary populates summary.actions → the
    // default report renders the "Recommended actions" Actions section.
    llmActions: [
      { title: 'Get listed on the top cited comparison page', detail: 'Reach out to the editor of the leading listicle.', priority: 'high', kind: 'gap' },
      { title: 'Publish a head-to-head comparison page', detail: 'Target the query where a rival wins.', priority: 'med', kind: 'compete' },
    ],
    results: [
      {
        query: 'Q1', queryText: 'best test brands 2026', provider: 'openai', label: 'ChatGPT',
        model: 'gpt-5-search-api', mode: 'web', mention: 'yes', position: 1, citationCount: 1,
        canonicalCitations: ['https://g2.com/categories/test'], competitors: ['RivalCo'], competitorsUnverified: [],
        responseQuality: 'ok', hasBrandInCitations: true, responseExcerpt: 'TestBrand is a strong option for teams.',
        elapsedMs: 100, inputTokens: 10, outputTokens: 10, costUsd: 0.54,
      },
      {
        query: 'Q2', queryText: 'best rival brands 2026', provider: 'openai', label: 'ChatGPT',
        model: 'gpt-5-search-api', mode: 'web', mention: 'src', position: null, citationCount: 1,
        canonicalCitations: ['https://capterra.com/p/test'], competitors: ['RivalCo'], competitorsUnverified: [],
        responseQuality: 'ok', hasBrandInCitations: true, responseExcerpt: 'RivalCo leads, though others appear.',
        elapsedMs: 100, inputTokens: 10, outputTokens: 10, costUsd: 0.54,
      },
    ],
  };
  writeFileSync(join(dd, '_summary.json'), JSON.stringify(summary));
  return today;
}

function renderBoth(dir, extraArgs = []) {
  const today = todayDateString();
  const r = spawnCli(['report', '--no-open', ...extraArgs], { cwd: dir, env: KEYS });
  assertExitCode(r, 0, `report ${extraArgs.join(' ')} should exit 0`);
  return {
    html: readFileSync(join(reportsDateDir(dir, DOMAIN, today), 'report.html'), 'utf-8'),
    md: readFileSync(join(reportsDateDir(dir, DOMAIN, today), 'report.md'), 'utf-8'),
  };
}

test('default report (HTML + MD) carries the tool fingerprint, the MC bridge, the Actions block AND the advisory/outreach copy', async () => {
  await withTmpProject('aeo-e2e-wl-default-', async (dir) => {
    seedSummary(dir);
    const { html, md } = renderBoth(dir);

    // Fingerprint surfaces present in the default report (the strip targets).
    assert.match(html, /aeo-platform/, 'default HTML should carry the aeo-platform wordmark');
    assert.match(html, /<article[^>]*\bid="mc-bridge"/, 'default HTML should render the MC bridge anchor');
    assert.match(html, /Recommended actions/, 'default HTML should render the Actions block (from llmActions)');

    // The advisory branches the seed forces to render — present here so the
    // two-sided assertions below have real teeth. HTML hero/cells:
    assert.match(html, /Pitch the top 3 first/, 'default HTML domain-SOV title should be the advisory "Pitch the top 3 first"');
    assert.match(html, /concentrate outreach/, 'default HTML category sub should carry "concentrate outreach"');
    assert.match(html, /\.outreach-item/, 'default HTML <style> should carry the .outreach-* CSS rules');
    // The lift CTA renders on BOTH surfaces in the default report (seed is
    // 1 yes + 1 src → kind 'lift'): the HTML hero KPI and the markdown run
    // verdict compose it from the same run-metrics.buildLiftNarrative halves.
    assert.match(html, /shortest lift/, 'default HTML hero should carry the lift CTA');
    assert.match(md, /shortest lift/, 'default MD run verdict should carry the lift CTA');
    // MD citation sections:
    assert.match(md, /Outreach templates/, 'default MD domain-SOV sub should reference "Outreach templates"');
    assert.match(md, /Outreach move/, 'default MD category table should carry the "Outreach move" column');
    assert.match(md, /Where to get mentioned/, 'default MD should carry the "Where to get mentioned" section');
    assert.match(md, /guest post/, 'default MD canonical-sources should carry "guest post" actions');
    assert.match(md, /closing the gap/, 'default MD competitors sub should carry "closing the gap"');
  });
});

test('report --white-label (HTML + MD) produces zero fingerprint AND zero advisory matches, drops bridge + actions, keeps a neutral title', async () => {
  await withTmpProject('aeo-e2e-wl-clean-', async (dir) => {
    seedSummary(dir);
    const today = todayDateString();
    const title = 'AEO Visibility Snapshot — testbrand.com';
    const r = spawnCli(
      ['report', '--no-open', '--white-label', '--report-title', title],
      { cwd: dir, env: KEYS },
    );
    assertExitCode(r, 0, 'report --white-label should exit 0');
    const html = readFileSync(join(reportsDateDir(dir, DOMAIN, today), 'report.html'), 'utf-8');
    const md = readFileSync(join(reportsDateDir(dir, DOMAIN, today), 'report.md'), 'utf-8');

    // (1) Fingerprint denylist — ZERO matches in BOTH files.
    for (const re of FINGERPRINT_DENYLIST) {
      assert.doesNotMatch(html, re, `white-label HTML must not match fingerprint ${re}`);
      assert.doesNotMatch(md, re, `white-label MD must not match fingerprint ${re}`);
    }

    // (2) Advisory / outreach denylist — ZERO matches in BOTH files. THIS is the
    // class the gate-1 test missed (HTML-only + no outreach tokens).
    for (const re of ADVISORY_DENYLIST) {
      assert.doesNotMatch(html, re, `white-label HTML must not match advisory ${re}`);
      assert.doesNotMatch(md, re, `white-label MD must not match advisory ${re}`);
    }

    // (3) MC bridge + Actions + outreach drafts gone (HTML).
    assert.doesNotMatch(html, /<article[^>]*\bid="mc-bridge"/, 'white-label must drop the MC bridge anchor');
    assert.doesNotMatch(html, /Recommended actions/, 'white-label must drop the Actions / recommendation block');
    assert.doesNotMatch(html, /Outreach drafts/, 'white-label must not render outreach drafts');
    assert.doesNotMatch(html, /Webappski plan/, 'white-label must not render the Webappski commerce fork');

    // (4) Neutral, parameterizable title + honest methodology footer present (both).
    assert.match(html, /<title>AEO Visibility Snapshot — testbrand\.com<\/title>/, 'white-label must use the neutral --report-title');
    assert.match(html, /Methodology: \d+ buyer-intent quer/, 'white-label HTML must carry the honest methodology footer');
    assert.match(html, /no confidence intervals are implied/, 'HTML methodology must disclaim statistics it does not have');
    assert.match(md, /Methodology: \d+ buyer-intent quer/, 'white-label MD must carry the honest methodology footer');
    assert.match(md, /no confidence intervals are implied/, 'MD methodology must disclaim statistics it does not have');

    // (5) The statistics survive — this is still a real report (both files).
    assert.match(html, /Unified Visibility Index/i, 'white-label HTML must keep the score/UVI');
    assert.match(html, /RivalCo/, 'white-label HTML must keep the competitors table');
    assert.match(md, /Competitors vs you/, 'white-label MD must keep the competitors section');
    assert.match(md, /RivalCo/, 'white-label MD must keep the competitor barchart');
    // The neutralised citation sections keep their statistics, just no advice.
    assert.match(md, /Domain Share of Voice/i, 'white-label MD must keep the domain share-of-voice table');
    assert.match(md, /Citation Sources/, 'white-label MD must keep the (renamed) citation-sources table');
    assert.match(md, /g2\.com/, 'white-label MD must keep the cited domains');
  });
});

test('report --white-label without --report-title falls back to a neutral brand+date title (no tool name)', async () => {
  await withTmpProject('aeo-e2e-wl-deftitle-', async (dir) => {
    seedSummary(dir);
    const today = todayDateString();
    const { html, md } = renderBoth(dir, ['--white-label']);
    assert.match(html, /<title>AEO Visibility Snapshot — testbrand\.com · [\d-]+<\/title>/, 'default white-label title is neutral');
    for (const re of [...FINGERPRINT_DENYLIST, ...ADVISORY_DENYLIST]) {
      assert.doesNotMatch(html, re, `default-title white-label HTML must not match ${re}`);
      assert.doesNotMatch(md, re, `default-title white-label MD must not match ${re}`);
    }
  });
});

// ────────────────────────────────────────────────────────────────────────────
// AP-REPORT-ANSWER-REVEAL — click-to-reveal verbatim engine answers behind each
// query×engine matrix cell, in BOTH default and white-label HTML.
//
// The full answer is MEASURED DATA, not tool/agency copy. It is shown in both
// modes. So the leak surface inside a reveal is NOT advisory words ("recommend /
// best / fastest" are the engine's own words on real CDN-style answers) — it is
// the tool/agency IDENTITY fingerprint (aeo-platform / webappski / mc-bridge),
// which must be 0 in white-label INCLUDING the embedded answer text. The
// reveal-specific tests below scan the embedded answers explicitly for the
// IDENTITY subset, while keeping the full advisory ban on the generated chrome
// (covered by the white-label tests above, whose seed has no raw files so the
// reveal falls back to clean excerpts).
//
// Mutation-sanity (run by hand to confirm teeth) — each MUST go RED:
//   - bin/aeo-tracker.js rawResponses loader: revert the model-suffixed name
//     resolution to the bare `q${qi}-${r.provider}.json` → the suffixed raw
//     files no longer load → reveal falls back to the excerpt → the "full text
//     present" assertion (longer than the excerpt, exact closing sentence) RED.
//   - html.js reveal: drop the `esc(fullText)` escape (emit raw) → the seeded
//     `<script>`/`<b>` payload renders live → the "answer is HTML-escaped" RED.
//   - html.js reveal: remove the `responseExcerpt` fallback branch → the
//     no-raw-file cell stops revealing → the fallback test RED.

// IDENTITY-only fingerprints — these must be 0 even inside embedded answers.
// (A real engine answer about CDNs never says "aeo-platform" / "webappski".)
const IDENTITY_FINGERPRINT = [
  /aeo-platform/i,
  /@webappski/i,
  /webappski/i,
  /mission ?control/i,
  /mc-bridge/i,
];

// A "named" cell needs a query+provider with mention:'yes' and a matching raw
// JSON file named `q{N}-{provider}-{sanitizedModel}.json` (the name the run
// writer produces — and the name the fixed report loader resolves).
function seedRevealProject(dir, { fullText, withRawFile = true } = {}) {
  const today = todayDateString();
  const dd = responsesDateDir(dir, DOMAIN, today);
  mkdirSync(dd, { recursive: true });
  // The full answer the reveal must surface verbatim. CLEAN of advisory words
  // (so the white-label advisory ban still holds) but carries a unique closing
  // sentence + an HTML-injection payload to prove (a) full text — not excerpt —
  // and (b) escaping.
  const answer = fullText || (
    'TestBrand operates a global network with strong price-to-performance. '
    + 'It appears across several category comparisons this period. '
    + 'A <script>alert(1)</script> token and an ampersand & angle < bracket are '
    + 'embedded to verify HTML escaping. '
    + 'UNIQUE_CLOSING_SENTENCE_THAT_NO_EXCERPT_WOULD_CONTAIN_END.'
  );
  const summary = {
    date: today,
    brand: 'TestBrand',
    domain: 'testbrand.com',
    score: 50,
    mentions: 1,
    total: 1,
    topCompetitors: [{ name: 'RivalCo', count: 2 }],
    results: [
      {
        query: 'Q1', queryText: 'best test brands 2026', provider: 'openai', label: 'ChatGPT',
        model: 'gpt-5-search-api', mode: 'web', mention: 'yes', position: 1, citationCount: 1,
        canonicalCitations: ['https://testbrand.com/page'], competitors: ['RivalCo'], competitorsUnverified: [],
        responseQuality: 'ok', hasBrandInCitations: true,
        // A SHORT excerpt — distinct from the full answer so the "full not
        // excerpt" assertion has teeth (the excerpt lacks the unique sentence).
        responseExcerpt: 'TestBrand operates a global network with strong price-to-performance.',
        elapsedMs: 100, inputTokens: 10, outputTokens: 10, costUsd: 0.5,
      },
    ],
  };
  writeFileSync(join(dd, '_summary.json'), JSON.stringify(summary));
  if (withRawFile) {
    // Model-suffixed name the writer produces — the fixed loader must resolve it.
    writeFileSync(
      join(dd, 'q1-openai-gpt-5-search-api.json'),
      JSON.stringify({ choices: [{ message: { content: answer } }] }),
    );
  }
  return { today, answer };
}

test('reveal: default HTML carries a per-cell <details> with the FULL, HTML-escaped verbatim answer', async () => {
  await withTmpProject('aeo-e2e-reveal-default-', async (dir) => {
    const { today } = seedRevealProject(dir);
    const r = spawnCli(['report', '--no-open'], { cwd: dir, env: KEYS });
    assertExitCode(r, 0, 'report should exit 0');
    const html = readFileSync(join(reportsDateDir(dir, DOMAIN, today), 'report.html'), 'utf-8');

    // (a) the reveal accordion exists with a non-empty answer body.
    assert.match(html, /<details class="reveal">/, 'default HTML must render the reveal <details>');
    assert.match(html, /<span class="reveal-q">best test brands 2026<\/span>/, 'reveal summary must be headed by the query text itself, not a Q-index');
    assert.match(html, /<div class="reveal-excerpt">[^<]/, 'reveal body must be non-empty');

    // FULL answer, not the truncated excerpt — the unique closing sentence is in
    // the full answer only, and the cell is NOT tagged "excerpt".
    assert.match(html, /UNIQUE_CLOSING_SENTENCE_THAT_NO_EXCERPT_WOULD_CONTAIN_END\./, 'reveal must carry the FULL answer (unique sentence present)');
    const revealBlock = html.slice(html.indexOf('<details class="reveal">'));
    assert.doesNotMatch(revealBlock.split('</details>')[0], /reveal-trunc/, 'a cell WITH a raw file must NOT be tagged as an excerpt fallback');

    // (b) the answer is HTML-ESCAPED — the injection payload is inert text, the
    // live page has no <script>alert / unescaped tag from the answer.
    assert.match(html, /&lt;script&gt;alert\(1\)&lt;\/script&gt;/, 'injected <script> must be HTML-escaped');
    assert.doesNotMatch(html, /<script>alert\(1\)<\/script>/, 'the answer must NOT inject a live <script>');

    // print-open JS present so Save-as-PDF expands every reveal.
    assert.match(html, /addEventListener\('beforeprint'/, 'print-open listener must be wired');
  });
});

test('reveal: white-label HTML embeds the FULL answer and is IDENTITY-fingerprint-free INCLUDING the embedded answer text', async () => {
  await withTmpProject('aeo-e2e-reveal-wl-', async (dir) => {
    const { today } = seedRevealProject(dir);
    const r = spawnCli(['report', '--no-open', '--white-label'], { cwd: dir, env: KEYS });
    assertExitCode(r, 0, 'report --white-label should exit 0');
    const html = readFileSync(join(reportsDateDir(dir, DOMAIN, today), 'report.html'), 'utf-8');

    // The reveal renders in white-label too (the answer is measured data).
    assert.match(html, /<details class="reveal">/, 'white-label HTML must still render the reveal <details>');
    assert.match(html, /UNIQUE_CLOSING_SENTENCE_THAT_NO_EXCERPT_WOULD_CONTAIN_END\./, 'white-label reveal must carry the full answer');

    // The WHOLE file — chrome AND embedded answers — is free of the tool/agency
    // IDENTITY fingerprint. This is the load-bearing white-label leak claim for
    // the reveal: the embedded answer text adds no identity tell.
    for (const re of IDENTITY_FINGERPRINT) {
      assert.doesNotMatch(html, re, `white-label HTML (incl. embedded answers) must not match identity ${re}`);
    }
    // The embedded answer region specifically — scan just the reveal bodies.
    const bodies = [...html.matchAll(/<div class="reveal-excerpt">([\s\S]*?)<\/div>/g)].map(m => m[1]);
    assert.ok(bodies.length > 0, 'white-label must have at least one embedded answer');
    for (const body of bodies) {
      for (const re of IDENTITY_FINGERPRINT) {
        assert.doesNotMatch(body, re, `embedded answer must not match identity ${re}`);
      }
    }
  });
});

test('reveal: a cell with NO raw file gracefully falls back to the excerpt and the render still succeeds (never-fail)', async () => {
  await withTmpProject('aeo-e2e-reveal-fallback-', async (dir) => {
    const { today } = seedRevealProject(dir, { withRawFile: false });
    const r = spawnCli(['report', '--no-open'], { cwd: dir, env: KEYS });
    // Never-fail: a cell with no captured answer must NOT break the render.
    assertExitCode(r, 0, 'report must still exit 0 when a cell has no raw file');
    const html = readFileSync(join(reportsDateDir(dir, DOMAIN, today), 'report.html'), 'utf-8');

    // Reveal still renders, sourced from the excerpt, tagged as such.
    assert.match(html, /<details class="reveal">/, 'reveal must still render from the excerpt');
    assert.match(html, /<span class="reveal-trunc">excerpt<\/span>/, 'a no-raw-file cell must be tagged "excerpt"');
    assert.match(html, /TestBrand operates a global network/, 'the excerpt text must be present');
    // The full-only sentence is absent (we never had the raw file).
    assert.doesNotMatch(html, /UNIQUE_CLOSING_SENTENCE_THAT_NO_EXCERPT_WOULD_CONTAIN_END/, 'no full answer without a raw file');
  });
});
